workflows:
  shorebird-ios-build:
    name: Shorebird Build (iOS Unsigned)
    max_build_duration: 60
    environment:
      flutter: stable # Specify the Flutter channel (stable, beta, dev)
      xcode: latest # Use the latest version of Xcode for iOS builds
      groups:
        - shorebird # Reference the variable group


    scripts:
      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods
          pod --version
          flutter pub get
          flutter pub upgrade
      - name: Install Flutter and Shorebird CLI
        script: |
          flutter --version
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          export PATH="$HOME/.shorebird/bin:$PATH"  >> $CM_ENV
          echo $PATH
          shorebird --version
          cd ios
          pod init
#          pod repo update
#          pod update Sentry/HybridSDK
          pod install
          cd ..
      - name: Shorebird Release
        script: flutter build ios
    artifacts:
      - build/ios/ipa/*.ipa # Unsigned iOS IPA file
#      - shorebird/*.patch # Shorebird patch files
