definitions:
  environment:
    shared_env: &shared_env
      flutter: 3.24.3
      groups:
        # Export the shorebird group to make $SHOREBIRD_TOKEN available to
        #   the Shorebird CLI.
        - shorebird
        # Export the app_store group to make the iOS code signing variables
        #   available the scripts below.
        - app_store
      vars:
        # The bundle ID of this example app.
        # Replace this with your app's bundle id.
        BUNDLE_ID: com.minatpay
        FLUTTER_VERSION: 3.24.1
scripts:
    # Download the Shorebird CLI and add it to the PATH.
    - &shorebird_install
      name: Install Shorebird
      script: |
        # Install Shorebird
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

        # Add Shorebird to PATH
        echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
    - &use_profiles
      # This generates an export_options.plist file that tells Xcode
      #   how to package our app. We explicitly set
      #   manageAppVersionAndBuildNumber so that we can control which
      #   version and build number are used for releasing and patching.
      name: Set up code signing settings on Xcode project
      script: |
        xcode-project use-profiles --custom-export-options={\"manageAppVersionAndBuildNumber\":false}
    - &fetch_dependencies
      name: Fetch Dependencies
      script: |
        flutter pub get

workflows:
  release-ios-workflow:
    name: Release iOS
    # This needs to run on a Mac instance.
    instance_type: mac_mini_m1

    environment:
      <<: *shared_env
      # Tell Codemagic+ that we're signing our app for App Store distribution
      #   and to use the bundle ID we defined above.

    scripts:
      # Use the scripts we defined in the definitions section.
      - *shorebird_install
      - *fetch_dependencies
      - *fetch_signing_files
      - *ios_initialize_keychain
      - *add_certs_to_keychain
      - *use_profiles
      - name: Shorebird Release
        # Run `shorebird release ios` to create a release.
        script: |
          shorebird release ios \
            --flutter-version="$FLUTTER_VERSION" \
            --export-options-plist=/Users/builder/export_options.plist
    # Tell Codemagic where to find the artifacts generated by
    #   the `shorebird release ios` command.
    artifacts:
      - build/ios/ipa/*.ipa





