workflows:
  shorebird-ios-build:
    name: Shorebird Build (iOS Unsigned)
    max_build_duration: 60
    environment:
      flutter: stable # Specify the Flutter channel (stable, beta, dev)
      xcode: latest # Use the latest version of Xcode for iOS builds
      groups:
        - broswestation # Reference the variable group
    scripts:
      - name: Install Flutter and Shorebird CLI
        script: |
          flutter --version
          curl -sS https://install.shorebird.dev | bash
          shorebird --version
      - name: Configure Shorebird
        script: shorebird init --api-key=$SHOREBIRD_API_KEY
      - name: Build Unsigned iOS IPA with Shorebird
        script: shorebird build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa # Unsigned iOS IPA file
      - shorebird/*.patch # Shorebird patch files
