workflows:
  flutter-build:
    name: Flutter Build (iOS and Android)
    max_build_duration: 60
    environment:
      flutter: stable # Specify the Flutter channel (stable, beta, dev)
      xcode: latest # Use the latest version of Xcode for iOS builds

    scripts:
      - name: Install Flutter
        script: |
          flutter --version
      - name: Dependencies
        script: |
          flutter pub get
          pod install
      - name: Build iOS
        script: |
          flutter build ipa --no-codesign
    artifacts:
      ##- build/app/outputs/flutter-apk/app-release.apk # Android APK
      ##- build/app/outputs/flutter-apk/app-release.aab # Android App Bundle
      - build/ios/ipa/*.ipa # iOS IPA file
      - build/ios/archive/*.xcarchive # iOS xcarchive IPA file
