// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAvYUtL3wOioMF-LkMbNnju08tYGXfTOo',
    appId: '1:658009879471:web:eaeccc109799fdc883355a',
    messagingSenderId: '658009879471',
    projectId: 'minatpay-67c72',
    authDomain: 'minatpay-67c72.firebaseapp.com',
    storageBucket: 'minatpay-67c72.firebasestorage.app',
    measurementId: 'G-S6ECLRQYVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTdrCKy06YrJ0AtGfOzOSrqo2KMVe4Fjg',
    appId: '1:658009879471:android:d219e9dbb099613183355a',
    messagingSenderId: '658009879471',
    projectId: 'minatpay-67c72',
    storageBucket: 'minatpay-67c72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx8rVgWL0n4nOkqzM3fUV6E6rv0bq2zu4',
    appId: '1:658009879471:ios:2297c01302ab621a83355a',
    messagingSenderId: '658009879471',
    projectId: 'minatpay-67c72',
    storageBucket: 'minatpay-67c72.firebasestorage.app',
    iosBundleId: 'com.minatpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx8rVgWL0n4nOkqzM3fUV6E6rv0bq2zu4',
    appId: '1:658009879471:ios:3ea3bdfe7b54d68f83355a',
    messagingSenderId: '658009879471',
    projectId: 'minatpay-67c72',
    storageBucket: 'minatpay-67c72.firebasestorage.app',
    iosBundleId: 'com.minatpay.ng.minatPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAvYUtL3wOioMF-LkMbNnju08tYGXfTOo',
    appId: '1:658009879471:web:db969c4f4096ac7483355a',
    messagingSenderId: '658009879471',
    projectId: 'minatpay-67c72',
    authDomain: 'minatpay-67c72.firebaseapp.com',
    storageBucket: 'minatpay-67c72.firebasestorage.app',
    measurementId: 'G-C6K0NV8374',
  );

}