const String baseUrl = 'https://app882024.minatpay.com';
const String backendUrl = 'http://minatpay.com.ng/upload/mightyweb.json';
const String apiUrl = '$baseUrl/api';

const String signUpPath = '/signup';
const String loginPath = '/login';
const String loginVerify = '/verifypassword';
const String confirmOtp = '/confirmotp';
const String resendOtp = '/resendotp';
const String sendSms = '/sendcode';
const String sendOtp = '/sendotp';
const String resetPassword = '/resetpassword';
const String setPin = '/setpin';
const String verifyPin = '/verifypin';
const String getDataPlan = '/get-data-plan';
const String buyData = '/data-app';
const String buyAirtime = '/airtime';
// const String buyAirtime = '/airtime-test';
const String upgradeToAgent = '/upgradetoagent';
const String manualFunding = '/manualfunding';
const String couponFunding = '/couponfunding';
const String profileUpdate = '/profileupdate';
const String changePin = '/changepin';
const String changePassword = '/changepassword';
const String verifyMeter = '/verify-meter';
const String verifyBetting = '/verify-betting';
const String verifyCable = '/verify-cable';
const String getElectricityDisco = '/get-electricity-disco';
const String getBetting = '/get-betting';
const String getEpin = '/get-epins';
const String buyEpin = '/epins-app';
const String getAirtimeNetwork = '/get-network';
const String getDataAvailability = '/network-avaliability';
const String verifyNetwork = '/verify-network';
const String postBetting = '/betting';
const String postElectricity = '/electricity';
const String postCable = '/cable-app';
const String generatemonnify = '/generatemonnify';
const String generatepalmpay = '/generatepalmpay';
const String generatepsb = '/generatepsb';
const String getCableVariation = '/get-cable-variation-id';
const String getCable = '/get-cable';

const String transactionPath = '/getusertransactions';
const String singleTransactionPath = '/getusertransaction';
const String getUserDetails = '/getuserdetails';
const String storeDeviceToken = '/createappid';

//internet_connection_checker: ^2.0.0
